const mockPlayers2025 = [
  // ════════ SOLD PLAYERS (62) ════════
  { name: 'Cameron Green', role: 'All-Rounder', team: 'KKR', basePrice: 20000000, stats: 'Sold ₹25.20CR', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Matheesha Pathirana', role: 'Bowler', team: 'KKR', basePrice: 20000000, stats: 'Sold ₹18CR', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Prashant Veer', role: 'All-Rounder', team: 'CSK', basePrice: 3000000, stats: 'Sold ₹14.20CR', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Kartik Sharma', role: 'WK-Batsman', team: 'CSK', basePrice: 3000000, stats: 'Sold ₹14.20CR', nationality: 'Indian', category: 'Uncapped WK-Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Liam Livingstone', role: 'All-Rounder', team: 'SRH', basePrice: 20000000, stats: 'Sold ₹13CR', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Josh Inglis', role: 'WK-Batsman', team: 'LSG', basePrice: 7500000, stats: 'Sold ₹8.60CR', nationality: 'Overseas', category: 'Capped WK-Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Auqib Nabi', role: 'All-Rounder', team: 'DC', basePrice: 3000000, stats: 'Sold ₹8.40CR', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Ravi Bishnoi', role: 'Bowler', team: 'RR', basePrice: 20000000, stats: 'Sold ₹7.20CR', nationality: 'Indian', category: 'Capped Spinner', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Venkatesh Iyer', role: 'All-Rounder', team: 'RCB', basePrice: 20000000, stats: 'Sold ₹7CR', nationality: 'Indian', category: 'Capped All-Rounder', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Jason Holder', role: 'All-Rounder', team: 'GT', basePrice: 10000000, stats: 'Sold ₹7CR', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Ben Duckett', role: 'Batsman', team: 'DC', basePrice: 20000000, stats: 'Sold ₹5.80CR', nationality: 'Overseas', category: 'Capped Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Rahul Chahar', role: 'Bowler', team: 'CSK', basePrice: 7500000, stats: 'Sold ₹5.20CR', nationality: 'Indian', category: 'Capped Spinner', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Ben Dwarshuis', role: 'Bowler', team: 'PBKS', basePrice: 7500000, stats: 'Sold ₹4.40CR', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Pathum Nissanka', role: 'Batsman', team: 'DC', basePrice: 7500000, stats: 'Sold ₹4CR', nationality: 'Overseas', category: 'Capped Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Tejasvi Dahiya', role: 'WK-Batsman', team: 'KKR', basePrice: 3000000, stats: 'Sold ₹3CR', nationality: 'Indian', category: 'Uncapped WK-Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Akshat Raghuwanshi', role: 'Batsman', team: 'PBKS', basePrice: 3000000, stats: 'Sold ₹3.60CR', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Mustafizur Rahman', role: 'Bowler', team: 'KKR', basePrice: 10000000, stats: 'Sold ₹9.20CR', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Wanindu Hasaranga', role: 'All-Rounder', team: 'MI', basePrice: 20000000, stats: 'Sold ₹2.80CR', nationality: 'Overseas', category: 'Capped Spinner', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Rachin Ravindra', role: 'All-Rounder', team: 'KKR', basePrice: 20000000, stats: 'Sold ₹2CR', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Matt Henry', role: 'Bowler', team: 'CSK', basePrice: 10000000, stats: 'Sold ₹2CR', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Anrich Nortje', role: 'Bowler', team: 'LSG', basePrice: 20000000, stats: 'Sold ₹2CR', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Akeal Hosein', role: 'All-Rounder', team: 'CSK', basePrice: 5000000, stats: 'Sold ₹2CR', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Lungi Ngidi', role: 'Bowler', team: 'DC', basePrice: 5000000, stats: 'Sold ₹2CR', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Kyle Jamieson', role: 'All-Rounder', team: 'DC', basePrice: 7500000, stats: 'Sold ₹2CR', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Tom Banton', role: 'WK-Batsman', team: 'GT', basePrice: 3000000, stats: 'Sold ₹2CR', nationality: 'Overseas', category: 'Capped WK-Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Sarfaraz Khan', role: 'Batsman', team: 'CSK', basePrice: 7500000, stats: 'Sold ₹75L', nationality: 'Indian', category: 'Capped Batter', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Mukul Choudhary', role: 'All-Rounder', team: 'LSG', basePrice: 3000000, stats: 'Sold ₹2.60CR', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Akash Deep', role: 'Bowler', team: 'KKR', basePrice: 10000000, stats: 'Sold ₹1CR', nationality: 'Indian', category: 'Capped Fast Bowler', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Shivam Mavi', role: 'Bowler', team: 'SRH', basePrice: 7500000, stats: 'Sold ₹75L', nationality: 'Indian', category: 'Capped Fast Bowler', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Quinton de Kock', role: 'WK-Batsman', team: 'MI', basePrice: 10000000, stats: 'Sold ₹1CR', nationality: 'Overseas', category: 'Capped WK-Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'David Miller', role: 'Batsman', team: 'DC', basePrice: 20000000, stats: 'Sold ₹7.50CR', nationality: 'Overseas', category: 'Capped Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Naman Tiwari', role: 'All-Rounder', team: 'LSG', basePrice: 3000000, stats: 'Sold ₹1CR', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Adam Milne', role: 'Bowler', team: 'RR', basePrice: 7500000, stats: 'Sold ₹2.40CR', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Kuldeep Sen', role: 'Bowler', team: 'RR', basePrice: 3000000, stats: 'Sold ₹75L', nationality: 'Indian', category: 'Capped Fast Bowler', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Vicky Ostwal', role: 'Bowler', team: 'RCB', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Indian', category: 'Capped Spinner', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Jordan Cox', role: 'WK-Batsman', team: 'RCB', basePrice: 7500000, stats: 'Sold ₹75L', nationality: 'Overseas', category: 'Capped WK-Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Prithvi Shaw', role: 'Batsman', team: 'DC', basePrice: 7500000, stats: 'Sold ₹75L', nationality: 'Indian', category: 'Capped Batter', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Rahul Tripathi', role: 'Batsman', team: 'KKR', basePrice: 7500000, stats: 'Sold ₹75L', nationality: 'Indian', category: 'Capped Batter', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Tim Seifert', role: 'WK-Batsman', team: 'KKR', basePrice: 7500000, stats: 'Sold ₹1.50CR', nationality: 'Overseas', category: 'Capped WK-Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Matthew Short', role: 'Batsman', team: 'CSK', basePrice: 7500000, stats: 'Sold ₹1.50CR', nationality: 'Overseas', category: 'Capped Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Finn Allen', role: 'Batsman', team: 'PBKS', basePrice: 7500000, stats: 'Sold ₹1CR', nationality: 'Overseas', category: 'Capped Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Jacob Duffy', role: 'Bowler', team: 'MI', basePrice: 3000000, stats: 'Sold ₹1.20CR', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Sushant Mishra', role: 'Bowler', team: 'RR', basePrice: 3000000, stats: 'Sold ₹90L', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Ashok Sharma', role: 'Bowler', team: 'GT', basePrice: 3000000, stats: 'Sold ₹90L', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Yash Punja', role: 'Bowler', team: 'RR', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Prashant Solanki', role: 'All-Rounder', team: 'KKR', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Vignesh Puthur', role: 'Bowler', team: 'RR', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Shivang Kumar', role: 'Bowler', team: 'SRH', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Kartik Tyagi', role: 'Bowler', team: 'KKR', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Indian', category: 'Capped Fast Bowler', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Mangesh Yadav', role: 'Bowler', team: 'RCB', basePrice: 3000000, stats: 'Sold ₹75L', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Danish Malewar', role: 'Batsman', team: 'MI', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Mayank Rawat', role: 'WK-Batsman', team: 'MI', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Indian', category: 'Uncapped WK-Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Aman Rao', role: 'All-Rounder', team: 'CSK', basePrice: 3000000, stats: 'Sold ₹75L', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Sarthak Ranjan', role: 'Batsman', team: 'RCB', basePrice: 3000000, stats: 'Sold ₹40L', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Atharva Ankolekar', role: 'All-Rounder', team: 'DC', basePrice: 3000000, stats: 'Sold ₹75L', nationality: 'Indian', category: 'Capped All-Rounder', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Onkar Tukaram Tarmale', role: 'Batsman', team: 'PBKS', basePrice: 3000000, stats: 'Sold ₹50L', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Kanishk Chouhan', role: 'Bowler', team: 'PBKS', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Vishal Nishad', role: 'Bowler', team: 'PBKS', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Cooper Connolly', role: 'All-Rounder', team: 'SRH', basePrice: 3000000, stats: 'Sold ₹75L', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Jack Edwards', role: 'All-Rounder', team: 'SRH', basePrice: 3000000, stats: 'Sold ₹30L', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Luke Wood', role: 'Bowler', team: 'GT', basePrice: 3000000, stats: 'Sold ₹50L', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Adam Fraser-Milne', role: 'Bowler', team: 'DC', basePrice: 3000000, stats: 'Sold ₹75L', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },

  // ════════ UNSOLD PLAYERS (79) ════════
  { name: 'Jake Fraser-McGurk', role: 'Batsman', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Devon Conway', role: 'Batsman', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Gus Atkinson', role: 'Bowler', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Jamie Smith', role: 'WK-Batsman', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped WK-Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Gerald Coetzee', role: 'Bowler', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Maheesh Theekshana', role: 'Bowler', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Spinner', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Mujeeb Ur Rahman', role: 'Bowler', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Spinner', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Daryl Mitchell', role: 'All-Rounder', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Michael Bracewell', role: 'All-Rounder', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Sean Abbott', role: 'Bowler', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Alzarri Joseph', role: 'Bowler', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Daniel Lawrence', role: 'All-Rounder', team: '', basePrice: 20000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Spencer Johnson', role: 'Bowler', team: '', basePrice: 15000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Rahmanullah Gurbaz', role: 'WK-Batsman', team: '', basePrice: 15000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped WK-Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Riley Meredith', role: 'Bowler', team: '', basePrice: 15000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Jhye Richardson', role: 'Bowler', team: '', basePrice: 15000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Wiaan Mulder', role: 'All-Rounder', team: '', basePrice: 10000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Jonny Bairstow', role: 'WK-Batsman', team: '', basePrice: 10000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped WK-Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Fazalhaq Farooqi', role: 'Bowler', team: '', basePrice: 10000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Waqar Salamkheil', role: 'Bowler', team: '', basePrice: 10000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Spinner', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'William Sutherland', role: 'All-Rounder', team: '', basePrice: 10000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Nathan Smith', role: 'All-Rounder', team: '', basePrice: 7500000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Sediqullah Atal', role: 'Batsman', team: '', basePrice: 7500000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Batter', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Dasun Shanaka', role: 'All-Rounder', team: '', basePrice: 7500000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped All-Rounder', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Chetan Sakariya', role: 'Bowler', team: '', basePrice: 7500000, stats: 'UNSOLD', nationality: 'Indian', category: 'Capped Fast Bowler', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'K.S. Bharat', role: 'WK-Batsman', team: '', basePrice: 7500000, stats: 'UNSOLD', nationality: 'Indian', category: 'Capped WK-Batter', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Deepak Hooda', role: 'All-Rounder', team: '', basePrice: 7500000, stats: 'UNSOLD', nationality: 'Indian', category: 'Capped All-Rounder', isCapped: true, isOverseas: false, poolSource: '2025' },
  { name: 'Taskin Ahmed', role: 'Bowler', team: '', basePrice: 7500000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Richard Gleeson', role: 'Bowler', team: '', basePrice: 7500000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Capped Fast Bowler', isCapped: true, isOverseas: true, poolSource: '2025' },
  { name: 'Mahipal Lomror', role: 'All-Rounder', team: '', basePrice: 5000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Karn Sharma', role: 'Bowler', team: '', basePrice: 5000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Rajvardhan Hangargekar', role: 'All-Rounder', team: '', basePrice: 4000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'KM Asif', role: 'Bowler', team: '', basePrice: 4000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Aarya Desai', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Yash Dhull', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Abhinav Manohar', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Anmolpreet Singh', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Atharva Taide', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Abhinav Tejrana', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Vijay Shankar', role: 'All-Rounder', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Eden Apple Tom', role: 'All-Rounder', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Tanush Kotian', role: 'All-Rounder', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Kamlesh Nagarkoti', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Ruchit Ahir', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Sanvir Singh', role: 'All-Rounder', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Vansh Bedi', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Tushar Raheja', role: 'WK-Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped WK-Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Raj Limbani', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Simarjeet Singh', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Akash Madhwal', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Wahidullah Zadran', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Uncapped Bowler', isCapped: false, isOverseas: true, poolSource: '2025' },
  { name: 'Shivam Shukla', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Kartikeya Singh', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Murugan Ashwin', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Tejas Baroka', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'KC Cariappa', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Mohit Rathee', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Salman Nizar', role: 'All-Rounder', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'M. Dheeraj Kumar', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Tanay Thyagarajan', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Connor Esterhuizen', role: 'All-Rounder', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: true, poolSource: '2025' },
  { name: 'Irfan Umair', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Chintal Gandhi', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Daniel Lategan', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Overseas', category: 'Uncapped Bowler', isCapped: false, isOverseas: true, poolSource: '2025' },
  { name: 'Karan Lal', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Utkarsh Singh', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Ayush Vartak', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Jikku Bright', role: 'All-Rounder', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Izaz Sawariya', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Mani Sankar Mura Singh', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Manan Vohra', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Mayank Dagar', role: 'All-Rounder', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Money Grewal', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Macneil Noronha', role: 'All-Rounder', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped All-Rounder', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Siddharth Yadav', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Ritik Tada', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Chama Milind', role: 'Bowler', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Bowler', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'Swastik Chikara', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' },
  { name: 'RS Ambrish', role: 'Batsman', team: '', basePrice: 3000000, stats: 'UNSOLD', nationality: 'Indian', category: 'Uncapped Batter', isCapped: false, isOverseas: false, poolSource: '2025' }
];

module.exports = mockPlayers2025;
