// Year-wise player pools for the IPL Auction Simulator (2008 - 2025)
// Values: Base prices are in Rupees (e.g. 2 Crore = 20,000,000)

const playerPools = {
  "2025": [
    { name: "Rishabh Pant", role: "WK-Batter", team: "LSG", basePrice: 20000000, stats: "Runs: 3284, SR: 148.9", nationality: "Indian", category: "Marquee Set 1", isCapped: true, isOverseas: false },
    { name: "Shreyas Iyer", role: "Batter", team: "PBKS", basePrice: 20000000, stats: "Runs: 3127, SR: 125.2", nationality: "Indian", category: "Marquee Set 1", isCapped: true, isOverseas: false },
    { name: "Venkatesh Iyer", role: "All-Rounder", team: "KKR", basePrice: 20000000, stats: "Runs: 1324, Wkts: 15", nationality: "Indian", category: "Marquee Set 1", isCapped: true, isOverseas: false },
    { name: "Jos Buttler", role: "WK-Batter", team: "GT", basePrice: 20000000, stats: "Runs: 3582, SR: 147.5", nationality: "Overseas", category: "Marquee Set 1", isCapped: true, isOverseas: true },
    { name: "KL Rahul", role: "WK-Batter", team: "DC", basePrice: 20000000, stats: "Runs: 4683, SR: 134.6", nationality: "Indian", category: "Marquee Set 1", isCapped: true, isOverseas: false },
    { name: "Mitchell Starc", role: "Bowler", team: "DC", basePrice: 20000000, stats: "Wkts: 92, Econ: 7.95", nationality: "Overseas", category: "Marquee Set 1", isCapped: true, isOverseas: true },
    { name: "Yuzvendra Chahal", role: "Bowler", team: "PBKS", basePrice: 20000000, stats: "Wkts: 205, Econ: 7.65", nationality: "Indian", category: "Marquee Set 1", isCapped: true, isOverseas: false },
    { name: "Liam Livingstone", role: "All-Rounder", team: "RCB", basePrice: 20000000, stats: "Runs: 1024, Wkts: 22", nationality: "Overseas", category: "Marquee Set 1", isCapped: true, isOverseas: true },
    { name: "Virat Kohli", role: "Batter", team: "RCB", basePrice: 20000000, stats: "Runs: 8004, SR: 131.9", nationality: "Indian", category: "Marquee Set 2", isCapped: true, isOverseas: false },
    { name: "Jasprit Bumrah", role: "Bowler", team: "MI", basePrice: 20000000, stats: "Wkts: 165, Econ: 7.30", nationality: "Indian", category: "Marquee Set 2", isCapped: true, isOverseas: false },
    { name: "Rohit Sharma", role: "Batter", team: "MI", basePrice: 20000000, stats: "Runs: 6628, SR: 131.2", nationality: "Indian", category: "Marquee Set 2", isCapped: true, isOverseas: false },
    { name: "Heinrich Klaasen", role: "WK-Batter", team: "SRH", basePrice: 20000000, stats: "Runs: 981, SR: 172.5", nationality: "Overseas", category: "Marquee Set 2", isCapped: true, isOverseas: true },
    { name: "Nicholas Pooran", role: "WK-Batter", team: "LSG", basePrice: 20000000, stats: "Runs: 1762, SR: 160.2", nationality: "Overseas", category: "Marquee Set 2", isCapped: true, isOverseas: true },
    { name: "Rashid Khan", role: "Bowler", team: "GT", basePrice: 20000000, stats: "Wkts: 149, Econ: 6.70", nationality: "Overseas", category: "Marquee Set 2", isCapped: true, isOverseas: true },
    { name: "Ruturaj Gaikwad", role: "Batter", team: "CSK", basePrice: 20000000, stats: "Runs: 2284, SR: 135.5", nationality: "Indian", category: "Marquee Set 2", isCapped: true, isOverseas: false },
    { name: "Ravindra Jadeja", role: "All-Rounder", team: "CSK", basePrice: 20000000, stats: "Runs: 2958, Wkts: 160", nationality: "Indian", category: "Marquee Set 2", isCapped: true, isOverseas: false },
    { name: "Suryakumar Yadav", role: "Batter", team: "MI", basePrice: 20000000, stats: "Runs: 3594, SR: 143.5", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Yashasvi Jaiswal", role: "Batter", team: "RR", basePrice: 20000000, stats: "Runs: 1602, SR: 150.2", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Shubman Gill", role: "Batter", team: "GT", basePrice: 20000000, stats: "Runs: 3204, SR: 134.8", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Travis Head", role: "Batter", team: "SRH", basePrice: 20000000, stats: "Runs: 1120, SR: 180.5", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Rinku Singh", role: "Batter", team: "KKR", basePrice: 10000000, stats: "Runs: 890, SR: 143.0", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Rajat Patidar", role: "Batter", team: "RCB", basePrice: 20000000, stats: "Runs: 792, SR: 138.2", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Devdutt Padikkal", role: "Batter", team: "RCB", basePrice: 20000000, stats: "Runs: 1521, SR: 124.2", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Faf du Plessis", role: "Batter", team: "DC", basePrice: 20000000, stats: "Runs: 4571, SR: 136.2", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Hardik Pandya", role: "All-Rounder", team: "MI", basePrice: 20000000, stats: "Runs: 2520, Wkts: 64", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Axar Patel", role: "All-Rounder", team: "DC", basePrice: 15000000, stats: "Runs: 1654, Wkts: 122", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Sunil Narine", role: "All-Rounder", team: "KKR", basePrice: 20000000, stats: "Wkts: 180, Runs: 1524", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Andre Russell", role: "All-Rounder", team: "KKR", basePrice: 20000000, stats: "Runs: 2484, Wkts: 115", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Riyan Parag", role: "All-Rounder", team: "RR", basePrice: 20000000, stats: "Runs: 984, SR: 139.2", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Abhishek Sharma", role: "All-Rounder", team: "SRH", basePrice: 20000000, stats: "Runs: 1376, SR: 155.2", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Sam Curran", role: "All-Rounder", team: "CSK", basePrice: 20000000, stats: "Runs: 954, Wkts: 58", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Marcus Stoinis", role: "All-Rounder", team: "LSG", basePrice: 20000000, stats: "Runs: 1824, Wkts: 42", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Arshdeep Singh", role: "Bowler", team: "PBKS", basePrice: 20000000, stats: "Wkts: 90, Econ: 8.40", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Pat Cummins", role: "Bowler", team: "SRH", basePrice: 20000000, stats: "Wkts: 65, Econ: 8.25", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Kuldeep Yadav", role: "Bowler", team: "DC", basePrice: 15000000, stats: "Wkts: 92, Econ: 8.02", nationality: "Indian", category: "Capped Spinner", isCapped: true, isOverseas: false },
    { name: "Matheesha Pathirana", role: "Bowler", team: "CSK", basePrice: 15000000, stats: "Wkts: 42, Econ: 7.90", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Varun Chakaravarthy", role: "Bowler", team: "KKR", basePrice: 10000000, stats: "Wkts: 85, Econ: 7.50", nationality: "Indian", category: "Capped Spinner", isCapped: true, isOverseas: false },
    { name: "Josh Hazlewood", role: "Bowler", team: "RCB", basePrice: 20000000, stats: "Wkts: 45, Econ: 7.82", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Trent Boult", role: "Bowler", team: "MI", basePrice: 20000000, stats: "Wkts: 121, Econ: 7.92", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Mohammed Shami", role: "Bowler", team: "SRH", basePrice: 20000000, stats: "Wkts: 142, Econ: 8.10", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Suyash Sharma", role: "Bowler", team: "RCB", basePrice: 3000000, stats: "Wkts: 15, Econ: 7.80", nationality: "Indian", category: "Uncapped Bowler", isCapped: false, isOverseas: false },
    { name: "Harshit Rana", role: "Bowler", team: "KKR", basePrice: 3000000, stats: "Wkts: 25, Econ: 8.60", nationality: "Indian", category: "Uncapped Bowler", isCapped: false, isOverseas: false },
    { name: "Mayank Yadav", role: "Bowler", team: "LSG", basePrice: 3000000, stats: "Wkts: 7, Econ: 6.90", nationality: "Indian", category: "Uncapped Bowler", isCapped: false, isOverseas: false },
    { name: "Rahul Tewatia", role: "All-Rounder", team: "GT", basePrice: 5000000, stats: "Runs: 980, SR: 142.5", nationality: "Indian", category: "Uncapped All-Rounder", isCapped: false, isOverseas: false },
    { name: "Shahrukh Khan", role: "Batter", team: "GT", basePrice: 4000000, stats: "Runs: 512, SR: 135.8", nationality: "Indian", category: "Uncapped Batter", isCapped: false, isOverseas: false },
    { name: "Sameer Rizvi", role: "Batter", team: "DC", basePrice: 3000000, stats: "Runs: 215, SR: 141.2", nationality: "Indian", category: "Uncapped Batter", isCapped: false, isOverseas: false },
    { name: "David Warner", role: "Batter", team: "", basePrice: 20000000, stats: "Runs: 6565, SR: 139.6", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Jonny Bairstow", role: "WK-Batter", team: "", basePrice: 20000000, stats: "Runs: 1524, SR: 140.2", nationality: "Overseas", category: "Capped WK-Batter", isCapped: true, isOverseas: true },
    { name: "Shardul Thakur", role: "All-Rounder", team: "", basePrice: 20000000, stats: "Wkts: 89, Runs: 324", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false }
  ],
  "2024": [
    { name: "Mitchell Starc", role: "Bowler", team: "KKR", basePrice: 20000000, stats: "Wkts: 85, Econ: 7.80", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Pat Cummins", role: "All-Rounder", team: "SRH", basePrice: 20000000, stats: "Wkts: 50, Runs: 380", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Daryl Mitchell", role: "All-Rounder", team: "CSK", basePrice: 10000000, stats: "Runs: 850, SR: 135.2", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Harshal Patel", role: "Bowler", team: "PBKS", basePrice: 20000000, stats: "Wkts: 111, Econ: 8.40", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Alzarri Joseph", role: "Bowler", team: "RCB", basePrice: 10000000, stats: "Wkts: 28, Econ: 8.70", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Spencer Johnson", role: "Bowler", team: "GT", basePrice: 5000000, stats: "Wkts: 18, Econ: 8.10", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Sameer Rizvi", role: "Batter", team: "CSK", basePrice: 2000000, stats: "T20 Runs: 450, SR: 155.0", nationality: "Indian", category: "Uncapped Batter", isCapped: false, isOverseas: false },
    { name: "Dilshan Madushanka", role: "Bowler", team: "MI", basePrice: 5000000, stats: "Wkts: 12, Econ: 8.30", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Chris Woakes", role: "All-Rounder", team: "PBKS", basePrice: 20000000, stats: "Runs: 350, Wkts: 30", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Gerald Coetzee", role: "Bowler", team: "MI", basePrice: 20000000, stats: "Wkts: 24, Econ: 8.20", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Rachin Ravindra", role: "All-Rounder", team: "CSK", basePrice: 5000000, stats: "Runs: 450, Wkts: 8", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Travis Head", role: "Batter", team: "SRH", basePrice: 20000000, stats: "Runs: 850, SR: 145.6", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Wanindu Hasaranga", role: "All-Rounder", team: "SRH", basePrice: 15000000, stats: "Wkts: 45, Runs: 310", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Umesh Yadav", role: "Bowler", team: "GT", basePrice: 20000000, stats: "Wkts: 136, Econ: 8.35", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Steve Smith", role: "Batter", team: "", basePrice: 20000000, stats: "Runs: 2485, SR: 128.2", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Karun Nair", role: "Batter", team: "", basePrice: 5000000, stats: "Runs: 1496, SR: 127.8", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false }
  ],
  "2023": [
    { name: "Sam Curran", role: "All-Rounder", team: "PBKS", basePrice: 20000000, stats: "Runs: 610, Wkts: 42", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Cameron Green", role: "All-Rounder", team: "MI", basePrice: 20000000, stats: "T20 Runs: 800, Wkts: 10", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Ben Stokes", role: "All-Rounder", team: "CSK", basePrice: 20000000, stats: "Runs: 920, Wkts: 28", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Nicholas Pooran", role: "WK-Batter", team: "LSG", basePrice: 20000000, stats: "Runs: 912, SR: 151.2", nationality: "Overseas", category: "Capped WK-Batter", isCapped: true, isOverseas: true },
    { name: "Harry Brook", role: "Batter", team: "SRH", basePrice: 15000000, stats: "Runs: 350, SR: 137.5", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Mayank Agarwal", role: "Batter", team: "SRH", basePrice: 10000000, stats: "Runs: 2590, SR: 134.2", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Shivam Mavi", role: "Bowler", team: "GT", basePrice: 4000000, stats: "Wkts: 30, Econ: 8.20", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Jason Holder", role: "All-Rounder", team: "RR", basePrice: 20000000, stats: "Wkts: 49, Runs: 247", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Heinrich Klaasen", role: "WK-Batter", team: "SRH", basePrice: 10000000, stats: "Runs: 450, SR: 165.2", nationality: "Overseas", category: "Capped WK-Batter", isCapped: true, isOverseas: true },
    { name: "Phil Salt", role: "WK-Batter", team: "DC", basePrice: 20000000, stats: "Runs: 218, SR: 145.0", nationality: "Overseas", category: "Capped WK-Batter", isCapped: true, isOverseas: true },
    { name: "Kane Williamson", role: "Batter", team: "GT", basePrice: 20000000, stats: "Runs: 2101, SR: 126.0", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Adil Rashid", role: "Bowler", team: "SRH", basePrice: 20000000, stats: "Wkts: 12, Econ: 7.80", nationality: "Overseas", category: "Capped Spinner", isCapped: true, isOverseas: true },
    { name: "Manish Pandey", role: "Batter", team: "DC", basePrice: 10000000, stats: "Runs: 3808, SR: 121.5", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false }
  ],
  "2022": [
    { name: "Ishan Kishan", role: "WK-Batter", team: "MI", basePrice: 20000000, stats: "Runs: 1450, SR: 138.5", nationality: "Indian", category: "Capped WK-Batter", isCapped: true, isOverseas: false },
    { name: "Deepak Chahar", role: "Bowler", team: "CSK", basePrice: 20000000, stats: "Wkts: 59, Econ: 7.80", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Shreyas Iyer", role: "Batter", team: "KKR", basePrice: 20000000, stats: "Runs: 2375, SR: 124.0", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Liam Livingstone", role: "All-Rounder", team: "PBKS", basePrice: 10000000, stats: "Runs: 420, Wkts: 12", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Shardul Thakur", role: "All-Rounder", team: "DC", basePrice: 20000000, stats: "Wkts: 82, Runs: 250", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Harshal Patel", role: "Bowler", team: "RCB", basePrice: 20000000, stats: "Wkts: 78, Econ: 8.20", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Lockie Ferguson", role: "Bowler", team: "GT", basePrice: 20000000, stats: "Wkts: 36, Econ: 8.10", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Avesh Khan", role: "Bowler", team: "LSG", basePrice: 2000000, stats: "Wkts: 29, Econ: 7.90", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Rahul Tewatia", role: "All-Rounder", team: "GT", basePrice: 4000000, stats: "Runs: 520, Wkts: 22", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Nicholas Pooran", role: "WK-Batter", team: "SRH", basePrice: 15000000, stats: "Runs: 606, SR: 150.5", nationality: "Overseas", category: "Capped WK-Batter", isCapped: true, isOverseas: true },
    { name: "Wanindu Hasaranga", role: "All-Rounder", team: "RCB", basePrice: 10000000, stats: "Wkts: 26, Econ: 7.50", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Shikhar Dhawan", role: "Batter", team: "PBKS", basePrice: 20000000, stats: "Runs: 5784, SR: 126.8", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Kagiso Rabada", role: "Bowler", team: "PBKS", basePrice: 20000000, stats: "Wkts: 90, Econ: 8.12", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "David Warner", role: "Batter", team: "DC", basePrice: 20000000, stats: "Runs: 5449, SR: 140.0", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Suresh Raina", role: "Batter", team: "", basePrice: 20000000, stats: "Runs: 5528, SR: 136.7", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false }
  ],
  "2021": [
    { name: "Chris Morris", role: "All-Rounder", team: "RR", basePrice: 7500000, stats: "Runs: 610, Wkts: 80", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Kyle Jamieson", role: "All-Rounder", team: "RCB", basePrice: 7500000, stats: "T20 Wkts: 45, SR: 138.0", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Glenn Maxwell", role: "All-Rounder", team: "RCB", basePrice: 20000000, stats: "Runs: 1505, SR: 154.2", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Jhye Richardson", role: "Bowler", team: "PBKS", basePrice: 15000000, stats: "Wkts: 22, Econ: 7.90", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Krishnappa Gowtham", role: "All-Rounder", team: "CSK", basePrice: 2000000, stats: "Runs: 186, Wkts: 13", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Riley Meredith", role: "Bowler", team: "PBKS", basePrice: 4000000, stats: "Wkts: 16, Econ: 8.50", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Moeen Ali", role: "All-Rounder", team: "CSK", basePrice: 20000000, stats: "Runs: 309, Wkts: 10", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Shahrukh Khan", role: "All-Rounder", team: "PBKS", basePrice: 2000000, stats: "Runs: 250, SR: 140.0", nationality: "Indian", category: "Uncapped All-Rounder", isCapped: false, isOverseas: false },
    { name: "Shakib Al Hasan", role: "All-Rounder", team: "KKR", basePrice: 20000000, stats: "Wkts: 59, Runs: 746", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Steve Smith", role: "Batter", team: "DC", basePrice: 20000000, stats: "Runs: 2333, SR: 129.2", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true }
  ],
  "2020": [
    { name: "Pat Cummins", role: "Bowler", team: "KKR", basePrice: 20000000, stats: "Wkts: 32, Econ: 7.75", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Glenn Maxwell", role: "All-Rounder", team: "KXIP", basePrice: 20000000, stats: "Runs: 1397, SR: 161.0", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Chris Morris", role: "All-Rounder", team: "RCB", basePrice: 15000000, stats: "Runs: 517, Wkts: 69", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Sheldon Cottrell", role: "Bowler", team: "KXIP", basePrice: 5000000, stats: "Wkts: 15, Econ: 8.20", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Nathan Coulter-Nile", role: "Bowler", team: "MI", basePrice: 10000000, stats: "Wkts: 36, Econ: 7.60", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Piyush Chawla", role: "Bowler", team: "CSK", basePrice: 10000000, stats: "Wkts: 150, Econ: 7.82", nationality: "Indian", category: "Capped Spinner", isCapped: true, isOverseas: false },
    { name: "Sam Curran", role: "All-Rounder", team: "CSK", basePrice: 10000000, stats: "Runs: 242, Wkts: 23", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Eoin Morgan", role: "Batter", team: "KKR", basePrice: 15000000, stats: "Runs: 850, SR: 126.2", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Shimron Hetmyer", role: "Batter", team: "DC", basePrice: 5000000, stats: "Runs: 220, SR: 140.0", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Yashasvi Jaiswal", role: "Batter", team: "RR", basePrice: 2000000, stats: "Runs: 150, SR: 135.0", nationality: "Indian", category: "Uncapped Batter", isCapped: false, isOverseas: false }
  ],
  "2019": [
    { name: "Sam Curran", role: "All-Rounder", team: "KXIP", basePrice: 20000000, stats: "Runs: 95, Wkts: 11", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Jaydev Unadkat", role: "Bowler", team: "RR", basePrice: 15000000, stats: "Wkts: 78, Econ: 8.40", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Colin Ingram", role: "Batter", team: "DC", basePrice: 20000000, stats: "Runs: 1320, SR: 138.4", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Carlos Brathwaite", role: "All-Rounder", team: "KKR", basePrice: 7500000, stats: "Runs: 181, Wkts: 13", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Axar Patel", role: "All-Rounder", team: "DC", basePrice: 10000000, stats: "Runs: 850, Wkts: 69", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Mohit Sharma", role: "Bowler", team: "CSK", basePrice: 5000000, stats: "Wkts: 92, Econ: 8.20", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Shimron Hetmyer", role: "Batter", team: "RCB", basePrice: 5000000, stats: "Runs: 450, SR: 145.0", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Nicholas Pooran", role: "WK-Batter", team: "KXIP", basePrice: 7500000, stats: "Runs: 350, SR: 155.6", nationality: "Overseas", category: "Capped WK-Batter", isCapped: true, isOverseas: true },
    { name: "Varun Chakaravarthy", role: "Bowler", team: "KXIP", basePrice: 2000000, stats: "T20 Wkts: 12, Econ: 6.80", nationality: "Indian", category: "Uncapped Spinner", isCapped: false, isOverseas: false },
    { name: "Shivam Dube", role: "All-Rounder", team: "RCB", basePrice: 2000000, stats: "Runs: 180, Wkts: 5", nationality: "Indian", category: "Uncapped All-Rounder", isCapped: false, isOverseas: false }
  ],
  "2018": [
    { name: "Ben Stokes", role: "All-Rounder", team: "RR", basePrice: 20000000, stats: "Runs: 316, Wkts: 12", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "KL Rahul", role: "WK-Batter", team: "KXIP", basePrice: 20000000, stats: "Runs: 1420, SR: 135.6", nationality: "Indian", category: "Capped WK-Batter", isCapped: true, isOverseas: false },
    { name: "Manish Pandey", role: "Batter", team: "SRH", basePrice: 10000000, stats: "Runs: 2215, SR: 120.2", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Chris Lynn", role: "Batter", team: "KKR", basePrice: 20000000, stats: "Runs: 1280, SR: 141.2", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Glenn Maxwell", role: "All-Rounder", team: "DD", basePrice: 20000000, stats: "Runs: 1220, Wkts: 15", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Rashid Khan", role: "Bowler", team: "SRH", basePrice: 20000000, stats: "Wkts: 42, Econ: 6.62", nationality: "Overseas", category: "Capped Spinner", isCapped: true, isOverseas: true },
    { name: "Krunal Pandya", role: "All-Rounder", team: "MI", basePrice: 4000000, stats: "Runs: 480, Wkts: 20", nationality: "Indian", category: "Uncapped All-Rounder", isCapped: false, isOverseas: false },
    { name: "Ishan Kishan", role: "WK-Batter", team: "MI", basePrice: 4000000, stats: "Runs: 510, SR: 134.5", nationality: "Indian", category: "Uncapped WK-Batter", isCapped: false, isOverseas: false },
    { name: "Jofra Archer", role: "Bowler", team: "RR", basePrice: 4000000, stats: "Wkts: 22, Econ: 7.80", nationality: "Overseas", category: "Uncapped Bowler", isCapped: false, isOverseas: true },
    { name: "Sanju Samson", role: "WK-Batter", team: "RR", basePrice: 10000000, stats: "Runs: 1420, SR: 130.5", nationality: "Indian", category: "Capped WK-Batter", isCapped: true, isOverseas: false }
  ],
  "2014": [
    { name: "Yuvraj Singh", role: "All-Rounder", team: "RCB", basePrice: 20000000, stats: "Runs: 2100, Wkts: 35", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Dinesh Karthik", role: "WK-Batter", team: "DD", basePrice: 20000000, stats: "Runs: 2210, Catches: 85", nationality: "Indian", category: "Capped WK-Batter", isCapped: true, isOverseas: false },
    { name: "Kevin Pietersen", role: "Batter", team: "DD", basePrice: 20000000, stats: "Runs: 1001, SR: 134.8", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Mitchell Johnson", role: "Bowler", team: "KXIP", basePrice: 20000000, stats: "Wkts: 61, Econ: 7.70", nationality: "Overseas", category: "Capped Fast Bowler", isCapped: true, isOverseas: true },
    { name: "Glenn Maxwell", role: "All-Rounder", team: "KXIP", basePrice: 10000000, stats: "Runs: 510, SR: 165.4", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Corey Anderson", role: "All-Rounder", team: "MI", basePrice: 10000000, stats: "Runs: 350, Wkts: 12", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Steven Smith", role: "Batter", team: "RR", basePrice: 15000000, stats: "Runs: 850, SR: 128.0", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "Robin Uthappa", role: "Batter", team: "KKR", basePrice: 20000000, stats: "Runs: 1980, SR: 128.5", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Jacques Kallis", role: "All-Rounder", team: "KKR", basePrice: 20000000, stats: "Runs: 2320, Wkts: 65", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Murali Vijay", role: "Batter", team: "DD", basePrice: 20000000, stats: "Runs: 1720, SR: 122.4", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false }
  ],
  "2011": [
    { name: "Gautam Gambhir", role: "Batter", team: "KKR", basePrice: 9200000, stats: "Runs: 1820, SR: 122.5", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Yusuf Pathan", role: "All-Rounder", team: "KKR", basePrice: 9200000, stats: "Runs: 1120, Wkts: 30", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Robin Uthappa", role: "WK-Batter", team: "PWI", basePrice: 9200000, stats: "Runs: 1280, SR: 130.4", nationality: "Indian", category: "Capped WK-Batter", isCapped: true, isOverseas: false },
    { name: "Rohit Sharma", role: "Batter", team: "MI", basePrice: 9200000, stats: "Runs: 1450, SR: 129.2", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false },
    { name: "Irfan Pathan", role: "All-Rounder", team: "DD", basePrice: 9200000, stats: "Runs: 820, Wkts: 52", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Mahela Jayawardene", role: "Batter", team: "KTK", basePrice: 9200000, stats: "Runs: 1100, SR: 125.6", nationality: "Overseas", category: "Capped Batter", isCapped: true, isOverseas: true },
    { name: "David Hussey", role: "All-Rounder", team: "KXIP", basePrice: 9200000, stats: "Runs: 720, SR: 135.2", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Piyush Chawla", role: "Bowler", team: "KXIP", basePrice: 9200000, stats: "Wkts: 58, Econ: 7.60", nationality: "Indian", category: "Capped Spinner", isCapped: true, isOverseas: false },
    { name: "Ravindra Jadeja", role: "All-Rounder", team: "KTK", basePrice: 9200000, stats: "Runs: 512, Wkts: 28", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Saurabh Tiwary", role: "Batter", team: "RCB", basePrice: 4600000, stats: "Runs: 620, SR: 128.2", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false }
  ],
  "2008": [
    { name: "MS Dhoni", role: "WK-Batter", team: "CSK", basePrice: 16000000, stats: "T20 Runs: 1200, SR: 135.0", nationality: "Indian", category: "Marquee Set 1", isCapped: true, isOverseas: false },
    { name: "Andrew Symonds", role: "All-Rounder", team: "DCH", basePrice: 10000000, stats: "Runs: 820, Wkts: 12", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Sanath Jayasuriya", role: "All-Rounder", team: "MI", basePrice: 10000000, stats: "Runs: 950, Wkts: 15", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Ishant Sharma", role: "Bowler", team: "KKR", basePrice: 6000000, stats: "Wkts: 15, Econ: 7.80", nationality: "Indian", category: "Capped Fast Bowler", isCapped: true, isOverseas: false },
    { name: "Irfan Pathan", role: "All-Rounder", team: "KXIP", basePrice: 6000000, stats: "Runs: 450, Wkts: 25", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Albie Morkel", role: "All-Rounder", team: "CSK", basePrice: 9000000, stats: "Runs: 380, Wkts: 18", nationality: "Overseas", category: "Capped All-Rounder", isCapped: true, isOverseas: true },
    { name: "Brendon McCullum", role: "WK-Batter", team: "KKR", basePrice: 7000000, stats: "Runs: 620, SR: 145.0", nationality: "Overseas", category: "Capped WK-Batter", isCapped: true, isOverseas: true },
    { name: "Sachin Tendulkar", role: "Batter", team: "MI", basePrice: 16000000, stats: "Runs: 1800, SR: 120.0", nationality: "Indian", category: "Marquee Set 1", isCapped: true, isOverseas: false },
    { name: "Sourav Ganguly", role: "All-Rounder", team: "KKR", basePrice: 16000000, stats: "Runs: 1200, Wkts: 10", nationality: "Indian", category: "Capped All-Rounder", isCapped: true, isOverseas: false },
    { name: "Rahul Dravid", role: "Batter", team: "RCB", basePrice: 16000000, stats: "Runs: 1000, SR: 115.0", nationality: "Indian", category: "Capped Batter", isCapped: true, isOverseas: false }
  ]
};

module.exports = playerPools;
