// Auto-generated 2025 IPL Player pool
const mongoose = require('mongoose');
const Player = require('./models/Player');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/ipl-auction';

const players2025 = [
  {
    "name": "Rishabh Pant",
    "role": "WK-Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 3284, SR: 148.9, Avg: 35.31",
    "nationality": "Indian",
    "category": "Marquee Set 1",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "931581",
    "cricbuzzId": "9310",
    "iplId": "18",
    "runs": 3284,
    "strikeRate": 148.9,
    "average": 35.31,
    "hundreds": 1,
    "fifties": 18,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 93
  },
  {
    "name": "Shreyas Iyer",
    "role": "Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 3127, SR: 125.2, Avg: 31.59",
    "nationality": "Indian",
    "category": "Marquee Set 1",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "642519",
    "cricbuzzId": "9428",
    "iplId": "12",
    "runs": 3127,
    "strikeRate": 125.2,
    "average": 31.59,
    "hundreds": 0,
    "fifties": 21,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 89
  },
  {
    "name": "Venkatesh Iyer",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 1324, SR: 137.1 | Wkts: 15, Econ: 8.52",
    "nationality": "Indian",
    "category": "Marquee Set 1",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "851403",
    "cricbuzzId": "11586",
    "iplId": "",
    "runs": 1324,
    "strikeRate": 137.1,
    "average": 28.17,
    "hundreds": 1,
    "fifties": 8,
    "wickets": 15,
    "economy": 8.52,
    "bestBowling": "",
    "rating": 86
  },
  {
    "name": "KL Rahul",
    "role": "WK-Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 4683, SR: 134.6, Avg: 45.47",
    "nationality": "Indian",
    "category": "Marquee Set 1",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "422108",
    "cricbuzzId": "8733",
    "iplId": "19",
    "runs": 4683,
    "strikeRate": 134.6,
    "average": 45.47,
    "hundreds": 4,
    "fifties": 37,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 94
  },
  {
    "name": "Jos Buttler",
    "role": "WK-Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 3582, SR: 147.5, Avg: 38.11",
    "nationality": "Overseas",
    "category": "Marquee Set 1",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "308967",
    "cricbuzzId": "7919",
    "iplId": "182",
    "runs": 3582,
    "strikeRate": 147.5,
    "average": 38.11,
    "hundreds": 7,
    "fifties": 19,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 95
  },
  {
    "name": "Mitchell Starc",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 92, Econ: 7.95, Avg: 24.12",
    "nationality": "Overseas",
    "category": "Marquee Set 1",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "311592",
    "cricbuzzId": "8181",
    "iplId": "74",
    "runs": 0,
    "strikeRate": 0,
    "average": 24.12,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 92,
    "economy": 7.95,
    "bestBowling": "4/15",
    "rating": 91
  },
  {
    "name": "Jofra Archer",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 48, Econ: 7.43, Avg: 24.4",
    "nationality": "Overseas",
    "category": "Marquee Set 2",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "669855",
    "cricbuzzId": "10420",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 24.4,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 48,
    "economy": 7.43,
    "bestBowling": "3/15",
    "rating": 88
  },
  {
    "name": "Josh Hazlewood",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 45, Econ: 7.82, Avg: 28.51",
    "nationality": "Overseas",
    "category": "Marquee Set 2",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "288284",
    "cricbuzzId": "8182",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 28.51,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 45,
    "economy": 7.82,
    "bestBowling": "4/25",
    "rating": 89
  },
  {
    "name": "Mohammed Shami",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 142, Econ: 8.1, Avg: 27.2",
    "nationality": "Indian",
    "category": "Marquee Set 2",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "481896",
    "cricbuzzId": "7909",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 27.2,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 142,
    "economy": 8.1,
    "bestBowling": "4/11",
    "rating": 92
  },
  {
    "name": "Ishan Kishan",
    "role": "WK-Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 2644, SR: 135.8, Avg: 28.43",
    "nationality": "Indian",
    "category": "Marquee Set 2",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "720471",
    "cricbuzzId": "10276",
    "iplId": "",
    "runs": 2644,
    "strikeRate": 135.8,
    "average": 28.43,
    "hundreds": 0,
    "fifties": 16,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 88
  },
  {
    "name": "Liam Livingstone",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 1024, SR: 155.6 | Wkts: 22, Econ: 8.24",
    "nationality": "Overseas",
    "category": "Marquee Set 2",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "403902",
    "cricbuzzId": "10179",
    "iplId": "",
    "runs": 1024,
    "strikeRate": 155.6,
    "average": 28.4,
    "hundreds": 0,
    "fifties": 6,
    "wickets": 22,
    "economy": 8.24,
    "bestBowling": "",
    "rating": 88
  },
  {
    "name": "Marco Jansen",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 12500000,
    "stats": "Runs: 215, SR: 132.5 | Wkts: 25, Econ: 9.12",
    "nationality": "Overseas",
    "category": "Marquee Set 2",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "696401",
    "cricbuzzId": "13346",
    "iplId": "",
    "runs": 215,
    "strikeRate": 132.5,
    "average": 15.36,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 25,
    "economy": 9.12,
    "bestBowling": "3/25",
    "rating": 84
  },
  {
    "name": "Faf du Plessis",
    "role": "Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 4571, SR: 136.2, Avg: 35.71",
    "nationality": "Overseas",
    "category": "Batters Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "44828",
    "cricbuzzId": "1739",
    "iplId": "",
    "runs": 4571,
    "strikeRate": 136.2,
    "average": 35.71,
    "hundreds": 0,
    "fifties": 37,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 91
  },
  {
    "name": "Devon Conway",
    "role": "Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 924, SR: 138.6, Avg: 46.12",
    "nationality": "Overseas",
    "category": "Batters Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "379140",
    "cricbuzzId": "11462",
    "iplId": "",
    "runs": 924,
    "strikeRate": 138.6,
    "average": 46.12,
    "hundreds": 0,
    "fifties": 9,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 90
  },
  {
    "name": "Harry Brook",
    "role": "Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 190, SR: 123.4, Avg: 21.11",
    "nationality": "Overseas",
    "category": "Batters Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "911707",
    "cricbuzzId": "12162",
    "iplId": "",
    "runs": 190,
    "strikeRate": 123.4,
    "average": 21.11,
    "hundreds": 1,
    "fifties": 0,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 82
  },
  {
    "name": "Phil Salt",
    "role": "WK-Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 688, SR: 175.8, Avg: 34.4",
    "nationality": "Overseas",
    "category": "Batters Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "669365",
    "cricbuzzId": "10226",
    "iplId": "",
    "runs": 688,
    "strikeRate": 175.8,
    "average": 34.4,
    "hundreds": 0,
    "fifties": 6,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 88
  },
  {
    "name": "Devdutt Padikkal",
    "role": "Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 1521, SR: 124.2, Avg: 26.22",
    "nationality": "Indian",
    "category": "Batters Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1119026",
    "cricbuzzId": "12928",
    "iplId": "",
    "runs": 1521,
    "strikeRate": 124.2,
    "average": 26.22,
    "hundreds": 1,
    "fifties": 9,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 84
  },
  {
    "name": "Rahul Tripathi",
    "role": "Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 2221, SR: 136.4, Avg: 26.76",
    "nationality": "Indian",
    "category": "Batters Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "446763",
    "cricbuzzId": "8356",
    "iplId": "",
    "runs": 2221,
    "strikeRate": 136.4,
    "average": 26.76,
    "hundreds": 0,
    "fifties": 12,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 85
  },
  {
    "name": "Jake Fraser-McGurk",
    "role": "Batter",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 330, SR: 234.0, Avg: 36.67",
    "nationality": "Overseas",
    "category": "Batters Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "1168049",
    "cricbuzzId": "13835",
    "iplId": "",
    "runs": 330,
    "strikeRate": 234.0,
    "average": 36.67,
    "hundreds": 0,
    "fifties": 4,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 89
  },
  {
    "name": "Priyansh Arya",
    "role": "Batter",
    "team": "",
    "basePrice": 3000000,
    "stats": "Runs: 0, SR: 0.0, Avg: 0.0",
    "nationality": "Indian",
    "category": "Batters Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1175402",
    "cricbuzzId": "14723",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0.0,
    "average": 0.0,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 70
  },
  {
    "name": "Vaibhav Suryavanshi",
    "role": "Batter",
    "team": "",
    "basePrice": 3000000,
    "stats": "Runs: 0, SR: 0.0, Avg: 0.0",
    "nationality": "Indian",
    "category": "Batters Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1408688",
    "cricbuzzId": "20490",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0.0,
    "average": 0.0,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 72
  },
  {
    "name": "Bhuvneshwar Kumar",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 181, Econ: 7.56, Avg: 27.23",
    "nationality": "Indian",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "326016",
    "cricbuzzId": "1726",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 27.23,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 181,
    "economy": 7.56,
    "bestBowling": "5/19",
    "rating": 93
  },
  {
    "name": "Khaleel Ahmed",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 74, Econ: 8.52, Avg: 24.81",
    "nationality": "Indian",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "942645",
    "cricbuzzId": "10926",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 24.81,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 74,
    "economy": 8.52,
    "bestBowling": "3/21",
    "rating": 86
  },
  {
    "name": "Avesh Khan",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 68, Econ: 8.41, Avg: 26.4",
    "nationality": "Indian",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "694211",
    "cricbuzzId": "9781",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 26.4,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 68,
    "economy": 8.41,
    "bestBowling": "4/24",
    "rating": 86
  },
  {
    "name": "T Natarajan",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 67, Econ: 8.78, Avg: 26.1",
    "nationality": "Indian",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "800267",
    "cricbuzzId": "10834",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 26.1,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 67,
    "economy": 8.78,
    "bestBowling": "3/10",
    "rating": 87
  },
  {
    "name": "Arshdeep Singh",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 90, Econ: 8.4, Avg: 24.1",
    "nationality": "Indian",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1125976",
    "cricbuzzId": "13217",
    "iplId": "132",
    "runs": 0,
    "strikeRate": 0,
    "average": 24.1,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 90,
    "economy": 8.4,
    "bestBowling": "5/32",
    "rating": 91
  },
  {
    "name": "Prasidh Krishna",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 49, Econ: 8.92, Avg: 31.41",
    "nationality": "Indian",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "917159",
    "cricbuzzId": "10923",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 31.41,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 49,
    "economy": 8.92,
    "bestBowling": "4/30",
    "rating": 84
  },
  {
    "name": "Mukesh Kumar",
    "role": "Bowler",
    "team": "",
    "basePrice": 10000000,
    "stats": "Wkts: 24, Econ: 9.32, Avg: 25.4",
    "nationality": "Indian",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1150493",
    "cricbuzzId": "15418",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 25.4,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 24,
    "economy": 9.32,
    "bestBowling": "3/21",
    "rating": 83
  },
  {
    "name": "Akash Deep",
    "role": "Bowler",
    "team": "",
    "basePrice": 10000000,
    "stats": "Wkts: 6, Econ: 9.8, Avg: 36.4",
    "nationality": "Indian",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1176959",
    "cricbuzzId": "13511",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 36.4,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 6,
    "economy": 9.8,
    "bestBowling": "2/45",
    "rating": 81
  },
  {
    "name": "Noor Ahmad",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 25, Econ: 7.82, Avg: 26.4",
    "nationality": "Overseas",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "1182529",
    "cricbuzzId": "13867",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 26.4,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 25,
    "economy": 7.82,
    "bestBowling": "3/37",
    "rating": 86
  },
  {
    "name": "Wanindu Hasaranga",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 15000000,
    "stats": "Runs: 120, SR: 115.0 | Wkts: 36, Econ: 7.55",
    "nationality": "Overseas",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "784379",
    "cricbuzzId": "10927",
    "iplId": "",
    "runs": 120,
    "strikeRate": 115.0,
    "average": 12.0,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 36,
    "economy": 7.55,
    "bestBowling": "5/18",
    "rating": 89
  },
  {
    "name": "Maheesh Theekshana",
    "role": "Bowler",
    "team": "",
    "basePrice": 15000000,
    "stats": "Wkts: 34, Econ: 7.66, Avg: 28.1",
    "nationality": "Overseas",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "1138316",
    "cricbuzzId": "13898",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 28.1,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 34,
    "economy": 7.66,
    "bestBowling": "4/33",
    "rating": 87
  },
  {
    "name": "Kagiso Rabada",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 117, Econ: 8.05, Avg: 21.05",
    "nationality": "Overseas",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "550215",
    "cricbuzzId": "9585",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 21.05,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 117,
    "economy": 8.05,
    "bestBowling": "4/21",
    "rating": 91
  },
  {
    "name": "Anrich Nortje",
    "role": "Bowler",
    "team": "",
    "basePrice": 20000000,
    "stats": "Wkts: 60, Econ: 8.71, Avg: 25.3",
    "nationality": "Overseas",
    "category": "Bowlers Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "481979",
    "cricbuzzId": "11843",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 25.3,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 60,
    "economy": 8.71,
    "bestBowling": "3/33",
    "rating": 88
  },
  {
    "name": "Sam Curran",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 954, SR: 138.2 | Wkts: 58, Econ: 9.15",
    "nationality": "Overseas",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "662973",
    "cricbuzzId": "10982",
    "iplId": "",
    "runs": 954,
    "strikeRate": 138.2,
    "average": 22.4,
    "hundreds": 0,
    "fifties": 4,
    "wickets": 58,
    "economy": 9.15,
    "bestBowling": "4/11",
    "rating": 90
  },
  {
    "name": "Will Jacks",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 230, SR: 175.6 | Wkts: 3, Econ: 8.6",
    "nationality": "Overseas",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "897549",
    "cricbuzzId": "12170",
    "iplId": "",
    "runs": 230,
    "strikeRate": 175.6,
    "average": 32.86,
    "hundreds": 1,
    "fifties": 1,
    "wickets": 3,
    "economy": 8.6,
    "bestBowling": "1/10",
    "rating": 87
  },
  {
    "name": "Krunal Pandya",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 1654, SR: 132.8 | Wkts: 76, Econ: 7.36",
    "nationality": "Indian",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "471342",
    "cricbuzzId": "9553",
    "iplId": "",
    "runs": 1654,
    "strikeRate": 132.8,
    "average": 20.42,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 76,
    "economy": 7.36,
    "bestBowling": "3/14",
    "rating": 86
  },
  {
    "name": "Washington Sundar",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 378, SR: 117.5 | Wkts: 37, Econ: 7.54",
    "nationality": "Indian",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "719715",
    "cricbuzzId": "10945",
    "iplId": "",
    "runs": 378,
    "strikeRate": 117.5,
    "average": 15.12,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 37,
    "economy": 7.54,
    "bestBowling": "3/16",
    "rating": 84
  },
  {
    "name": "Axar Patel",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 1654, SR: 130.5 | Wkts: 122, Econ: 7.24",
    "nationality": "Indian",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "554691",
    "cricbuzzId": "8313",
    "iplId": "110",
    "runs": 1654,
    "strikeRate": 130.5,
    "average": 21.05,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 122,
    "economy": 7.24,
    "bestBowling": "4/21",
    "rating": 92
  },
  {
    "name": "Mitchell Marsh",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 666, SR: 125.4 | Wkts: 36, Econ: 8.4",
    "nationality": "Overseas",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "272450",
    "cricbuzzId": "6250",
    "iplId": "",
    "runs": 666,
    "strikeRate": 125.4,
    "average": 19.58,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 36,
    "economy": 8.4,
    "bestBowling": "4/27",
    "rating": 87
  },
  {
    "name": "Marcus Stoinis",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 1824, SR: 142.5 | Wkts: 42, Econ: 9.1",
    "nationality": "Overseas",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "325012",
    "cricbuzzId": "8183",
    "iplId": "",
    "runs": 1824,
    "strikeRate": 142.5,
    "average": 28.2,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 42,
    "economy": 9.1,
    "bestBowling": "4/15",
    "rating": 89
  },
  {
    "name": "Glenn Phillips",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 20000000,
    "stats": "Runs: 85, SR: 120.0 | Wkts: 1, Econ: 9.5",
    "nationality": "Overseas",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "823509",
    "cricbuzzId": "10471",
    "iplId": "",
    "runs": 85,
    "strikeRate": 120.0,
    "average": 14.16,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 1,
    "economy": 9.5,
    "bestBowling": "1/20",
    "rating": 83
  },
  {
    "name": "Azmatullah Omarzai",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 15000000,
    "stats": "Runs: 50, SR: 130.0 | Wkts: 4, Econ: 8.6",
    "nationality": "Overseas",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "819429",
    "cricbuzzId": "13247",
    "iplId": "",
    "runs": 50,
    "strikeRate": 130.0,
    "average": 12.5,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 4,
    "economy": 8.6,
    "bestBowling": "1/24",
    "rating": 82
  },
  {
    "name": "David Miller",
    "role": "Batter",
    "team": "",
    "basePrice": 15000000,
    "stats": "Runs: 2924, SR: 139.2, Avg: 36.12",
    "nationality": "Overseas",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "321777",
    "cricbuzzId": "576",
    "iplId": "",
    "runs": 2924,
    "strikeRate": 139.2,
    "average": 36.12,
    "hundreds": 1,
    "fifties": 12,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 90
  },
  {
    "name": "Abdul Samad",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 15000000,
    "stats": "Runs: 511, SR: 139.6 | Wkts: 2, Econ: 11.2",
    "nationality": "Indian",
    "category": "All-Rounders Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1205728",
    "cricbuzzId": "13809",
    "iplId": "",
    "runs": 511,
    "strikeRate": 139.6,
    "average": 18.25,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 2,
    "economy": 11.2,
    "bestBowling": "1/9",
    "rating": 81
  },
  {
    "name": "Quinton de Kock",
    "role": "WK-Batter",
    "team": "",
    "basePrice": 10000000,
    "stats": "Runs: 3157, SR: 134.2, Avg: 31.57",
    "nationality": "Overseas",
    "category": "Wicket-Keepers Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "379143",
    "cricbuzzId": "8359",
    "iplId": "",
    "runs": 3157,
    "strikeRate": 134.2,
    "average": 31.57,
    "hundreds": 2,
    "fifties": 23,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 91
  },
  {
    "name": "Ryan Rickelton",
    "role": "WK-Batter",
    "team": "",
    "basePrice": 10000000,
    "stats": "Runs: 0, SR: 0.0, Avg: 0.0",
    "nationality": "Overseas",
    "category": "Wicket-Keepers Set",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "605661",
    "cricbuzzId": "11026",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0.0,
    "average": 0.0,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 78
  },
  {
    "name": "Jitesh Sharma",
    "role": "WK-Batter",
    "team": "",
    "basePrice": 10000000,
    "stats": "Runs: 730, SR: 151.2, Avg: 22.81",
    "nationality": "Indian",
    "category": "Wicket-Keepers Set",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "721867",
    "cricbuzzId": "10141",
    "iplId": "",
    "runs": 730,
    "strikeRate": 151.2,
    "average": 22.81,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 83
  },
  {
    "name": "Suyash Sharma",
    "role": "Bowler",
    "team": "",
    "basePrice": 3000000,
    "stats": "Wkts: 10, Econ: 8.24, Avg: 32.1",
    "nationality": "Indian",
    "category": "Uncapped Indians Set",
    "isCapped": false,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1350792",
    "cricbuzzId": "18451",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 32.1,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 10,
    "economy": 8.24,
    "bestBowling": "3/30",
    "rating": 82
  },
  {
    "name": "Anshul Kamboj",
    "role": "Bowler",
    "team": "",
    "basePrice": 3000000,
    "stats": "Wkts: 8, Econ: 8.9, Avg: 26.5",
    "nationality": "Indian",
    "category": "Uncapped Indians Set",
    "isCapped": false,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1175428",
    "cricbuzzId": "13589",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 26.5,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 8,
    "economy": 8.9,
    "bestBowling": "3/27",
    "rating": 81
  },
  {
    "name": "Gurjapneet Singh",
    "role": "Bowler",
    "team": "",
    "basePrice": 3000000,
    "stats": "Wkts: 0, Econ: 0.0, Avg: 0.0",
    "nationality": "Indian",
    "category": "Uncapped Indians Set",
    "isCapped": false,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1269869",
    "cricbuzzId": "16124",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0,
    "average": 0.0,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 0,
    "economy": 0.0,
    "bestBowling": "-",
    "rating": 74
  },
  {
    "name": "Angkrish Raghuvanshi",
    "role": "Batter",
    "team": "",
    "basePrice": 3000000,
    "stats": "Runs: 163, SR: 155.2, Avg: 23.28",
    "nationality": "Indian",
    "category": "Uncapped Indians Set",
    "isCapped": false,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1292495",
    "cricbuzzId": "18456",
    "iplId": "",
    "runs": 163,
    "strikeRate": 155.2,
    "average": 23.28,
    "hundreds": 0,
    "fifties": 1,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 80
  },
  {
    "name": "Naman Dhir",
    "role": "Batter",
    "team": "",
    "basePrice": 3000000,
    "stats": "Runs: 140, SR: 165.2, Avg: 17.5",
    "nationality": "Indian",
    "category": "Uncapped Indians Set",
    "isCapped": false,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1159384",
    "cricbuzzId": "15638",
    "iplId": "",
    "runs": 140,
    "strikeRate": 165.2,
    "average": 17.5,
    "hundreds": 0,
    "fifties": 1,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 80
  },
  {
    "name": "Robin Minz",
    "role": "WK-Batter",
    "team": "",
    "basePrice": 3000000,
    "stats": "Runs: 0, SR: 0.0, Avg: 0.0",
    "nationality": "Indian",
    "category": "Uncapped Indians Set",
    "isCapped": false,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1350762",
    "cricbuzzId": "18524",
    "iplId": "",
    "runs": 0,
    "strikeRate": 0.0,
    "average": 0.0,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 75
  },
  {
    "name": "Arjun Tendulkar",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 3000000,
    "stats": "Runs: 13, SR: 144.4 | Wkts: 3, Econ: 9.36",
    "nationality": "Indian",
    "category": "Uncapped Indians Set",
    "isCapped": false,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1148776",
    "cricbuzzId": "13596",
    "iplId": "",
    "runs": 13,
    "strikeRate": 144.4,
    "average": 13.0,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 3,
    "economy": 9.36,
    "bestBowling": "1/9",
    "rating": 78
  },
  {
    "name": "Raj Angad Bawa",
    "role": "All-Rounder",
    "team": "",
    "basePrice": 3000000,
    "stats": "Runs: 11, SR: 110.0 | Wkts: 0, Econ: 12.0",
    "nationality": "Indian",
    "category": "Uncapped Indians Set",
    "isCapped": false,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1292502",
    "cricbuzzId": "14619",
    "iplId": "",
    "runs": 11,
    "strikeRate": 110.0,
    "average": 11.0,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 0,
    "economy": 12.0,
    "bestBowling": "-",
    "rating": 76
  },
  {
    "name": "Virat Kohli",
    "role": "Batter",
    "team": "RCB",
    "basePrice": 210000000,
    "stats": "Runs: 8004, SR: 131.9, Avg: 38.67",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "253802",
    "cricbuzzId": "1413",
    "iplId": "2",
    "runs": 8004,
    "strikeRate": 131.9,
    "average": 38.67,
    "hundreds": 8,
    "fifties": 55,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 98
  },
  {
    "name": "Jasprit Bumrah",
    "role": "Bowler",
    "team": "MI",
    "basePrice": 180000000,
    "stats": "Wkts: 165, Econ: 7.3, Avg: 22.51",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "625383",
    "cricbuzzId": "9311",
    "iplId": "9",
    "runs": 0,
    "strikeRate": 0,
    "average": 22.51,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 165,
    "economy": 7.3,
    "bestBowling": "5/10",
    "rating": 99
  },
  {
    "name": "Rohit Sharma",
    "role": "Batter",
    "team": "MI",
    "basePrice": 163000000,
    "stats": "Runs: 6628, SR: 131.2, Avg: 29.72",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "34102",
    "cricbuzzId": "1411",
    "iplId": "6",
    "runs": 6628,
    "strikeRate": 131.2,
    "average": 29.72,
    "hundreds": 2,
    "fifties": 43,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 94
  },
  {
    "name": "Suryakumar Yadav",
    "role": "Batter",
    "team": "MI",
    "basePrice": 163500000,
    "stats": "Runs: 3594, SR: 143.5, Avg: 32.08",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "446507",
    "cricbuzzId": "11803",
    "iplId": "108",
    "runs": 3594,
    "strikeRate": 143.5,
    "average": 32.08,
    "hundreds": 2,
    "fifties": 24,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 96
  },
  {
    "name": "Hardik Pandya",
    "role": "All-Rounder",
    "team": "MI",
    "basePrice": 163500000,
    "stats": "Runs: 2520, SR: 145.2 | Wkts: 64, Econ: 8.12",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "625371",
    "cricbuzzId": "9622",
    "iplId": "274",
    "runs": 2520,
    "strikeRate": 145.2,
    "average": 28.63,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 64,
    "economy": 8.12,
    "bestBowling": "3/17",
    "rating": 95
  },
  {
    "name": "Rashid Khan",
    "role": "Bowler",
    "team": "GT",
    "basePrice": 180000000,
    "stats": "Wkts: 149, Econ: 6.7, Avg: 20.8",
    "nationality": "Overseas",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "793463",
    "cricbuzzId": "10738",
    "iplId": "218",
    "runs": 0,
    "strikeRate": 0,
    "average": 20.8,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 149,
    "economy": 6.7,
    "bestBowling": "4/24",
    "rating": 98
  },
  {
    "name": "Shubman Gill",
    "role": "Batter",
    "team": "GT",
    "basePrice": 165000000,
    "stats": "Runs: 3204, SR: 134.8, Avg: 37.25",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1070173",
    "cricbuzzId": "11813",
    "iplId": "62",
    "runs": 3204,
    "strikeRate": 134.8,
    "average": 37.25,
    "hundreds": 3,
    "fifties": 18,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 94
  },
  {
    "name": "Ruturaj Gaikwad",
    "role": "Batter",
    "team": "CSK",
    "basePrice": 180000000,
    "stats": "Runs: 2284, SR: 135.5, Avg: 41.52",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1060380",
    "cricbuzzId": "11810",
    "iplId": "102",
    "runs": 2284,
    "strikeRate": 135.5,
    "average": 41.52,
    "hundreds": 2,
    "fifties": 18,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 95
  },
  {
    "name": "Ravindra Jadeja",
    "role": "All-Rounder",
    "team": "CSK",
    "basePrice": 180000000,
    "stats": "Runs: 2958, SR: 128.5 | Wkts: 160, Econ: 7.6",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "234675",
    "cricbuzzId": "587",
    "iplId": "9",
    "runs": 2958,
    "strikeRate": 128.5,
    "average": 27.38,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 160,
    "economy": 7.6,
    "bestBowling": "5/16",
    "rating": 96
  },
  {
    "name": "Sanju Samson",
    "role": "WK-Batter",
    "team": "RR",
    "basePrice": 180000000,
    "stats": "Runs: 4419, SR: 137.2, Avg: 30.68",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "425943",
    "cricbuzzId": "8271",
    "iplId": "258",
    "runs": 4419,
    "strikeRate": 137.2,
    "average": 30.68,
    "hundreds": 3,
    "fifties": 22,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 93
  },
  {
    "name": "Yashasvi Jaiswal",
    "role": "Batter",
    "team": "RR",
    "basePrice": 180000000,
    "stats": "Runs: 1602, SR: 150.2, Avg: 32.04",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1151278",
    "cricbuzzId": "13329",
    "iplId": "135",
    "runs": 1602,
    "strikeRate": 150.2,
    "average": 32.04,
    "hundreds": 2,
    "fifties": 9,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 92
  },
  {
    "name": "Heinrich Klaasen",
    "role": "WK-Batter",
    "team": "SRH",
    "basePrice": 230000000,
    "stats": "Runs: 981, SR: 172.5, Avg: 44.59",
    "nationality": "Overseas",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "436757",
    "cricbuzzId": "10734",
    "iplId": "202",
    "runs": 981,
    "strikeRate": 172.5,
    "average": 44.59,
    "hundreds": 0,
    "fifties": 6,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 95
  },
  {
    "name": "Pat Cummins",
    "role": "Bowler",
    "team": "SRH",
    "basePrice": 180000000,
    "stats": "Wkts: 65, Econ: 8.25, Avg: 27.5",
    "nationality": "Overseas",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "489889",
    "cricbuzzId": "8090",
    "iplId": "81",
    "runs": 0,
    "strikeRate": 0,
    "average": 27.5,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 65,
    "economy": 8.25,
    "bestBowling": "4/34",
    "rating": 91
  },
  {
    "name": "Travis Head",
    "role": "Batter",
    "team": "SRH",
    "basePrice": 140000000,
    "stats": "Runs: 1120, SR: 180.5, Avg: 36.12",
    "nationality": "Overseas",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "530011",
    "cricbuzzId": "8497",
    "iplId": "54",
    "runs": 1120,
    "strikeRate": 180.5,
    "average": 36.12,
    "hundreds": 1,
    "fifties": 4,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 94
  },
  {
    "name": "Abhishek Sharma",
    "role": "All-Rounder",
    "team": "SRH",
    "basePrice": 140000000,
    "stats": "Runs: 1376, SR: 155.2 | Wkts: 9, Econ: 8.6",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1070183",
    "cricbuzzId": "11815",
    "iplId": "155",
    "runs": 1376,
    "strikeRate": 155.2,
    "average": 25.01,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 9,
    "economy": 8.6,
    "bestBowling": "2/4",
    "rating": 88
  },
  {
    "name": "Nicholas Pooran",
    "role": "WK-Batter",
    "team": "LSG",
    "basePrice": 210000000,
    "stats": "Runs: 1762, SR: 160.2, Avg: 32.62",
    "nationality": "Overseas",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "604302",
    "cricbuzzId": "10225",
    "iplId": "136",
    "runs": 1762,
    "strikeRate": 160.2,
    "average": 32.62,
    "hundreds": 0,
    "fifties": 8,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 93
  },
  {
    "name": "Rinku Singh",
    "role": "Batter",
    "team": "KKR",
    "basePrice": 130000000,
    "stats": "Runs: 890, SR: 143.0, Avg: 35.6",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "723105",
    "cricbuzzId": "10833",
    "iplId": "152",
    "runs": 890,
    "strikeRate": 143.0,
    "average": 35.6,
    "hundreds": 0,
    "fifties": 4,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 89
  },
  {
    "name": "Varun Chakravarthy",
    "role": "Bowler",
    "team": "KKR",
    "basePrice": 120000000,
    "stats": "Wkts: 85, Econ: 7.5, Avg: 23.4",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1108375",
    "cricbuzzId": "12926",
    "iplId": "140",
    "runs": 0,
    "strikeRate": 0,
    "average": 23.4,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 85,
    "economy": 7.5,
    "bestBowling": "5/20",
    "rating": 90
  },
  {
    "name": "Sunil Narine",
    "role": "All-Rounder",
    "team": "KKR",
    "basePrice": 120000000,
    "stats": "Runs: 1524, SR: 162.8 | Wkts: 180, Econ: 6.63",
    "nationality": "Overseas",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "230558",
    "cricbuzzId": "8354",
    "iplId": "203",
    "runs": 1524,
    "strikeRate": 162.8,
    "average": 17.12,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 180,
    "economy": 6.63,
    "bestBowling": "5/19",
    "rating": 97
  },
  {
    "name": "Andre Russell",
    "role": "All-Rounder",
    "team": "KKR",
    "basePrice": 120000000,
    "stats": "Runs: 2484, SR: 174.0 | Wkts: 115, Econ: 9.2",
    "nationality": "Overseas",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "276298",
    "cricbuzzId": "7736",
    "iplId": "177",
    "runs": 2484,
    "strikeRate": 174.0,
    "average": 29.2,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 115,
    "economy": 9.2,
    "bestBowling": "4/20",
    "rating": 96
  },
  {
    "name": "Axar Patel",
    "role": "All-Rounder",
    "team": "DC",
    "basePrice": 165000000,
    "stats": "Runs: 1654, SR: 130.5 | Wkts: 122, Econ: 7.24",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "554691",
    "cricbuzzId": "8313",
    "iplId": "110",
    "runs": 1654,
    "strikeRate": 130.5,
    "average": 21.05,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 122,
    "economy": 7.24,
    "bestBowling": "4/21",
    "rating": 92
  },
  {
    "name": "Kuldeep Yadav",
    "role": "Bowler",
    "team": "DC",
    "basePrice": 132500000,
    "stats": "Wkts: 92, Econ: 8.02, Avg: 26.5",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "559235",
    "cricbuzzId": "8292",
    "iplId": "261",
    "runs": 0,
    "strikeRate": 0,
    "average": 26.5,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 92,
    "economy": 8.02,
    "bestBowling": "4/14",
    "rating": 92
  },
  {
    "name": "Arshdeep Singh",
    "role": "Bowler",
    "team": "PBKS",
    "basePrice": 180000000,
    "stats": "Wkts: 90, Econ: 8.4, Avg: 24.1",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "1125976",
    "cricbuzzId": "13217",
    "iplId": "132",
    "runs": 0,
    "strikeRate": 0,
    "average": 24.1,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 90,
    "economy": 8.4,
    "bestBowling": "5/32",
    "rating": 91
  },
  {
    "name": "Matheesha Pathirana",
    "role": "Bowler",
    "team": "CSK",
    "basePrice": 130000000,
    "stats": "Wkts: 42, Econ: 7.9, Avg: 21.4",
    "nationality": "Overseas",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": true,
    "poolSource": "2025",
    "espnId": "1194795",
    "cricbuzzId": "14757",
    "iplId": "147",
    "runs": 0,
    "strikeRate": 0,
    "average": 21.4,
    "hundreds": 0,
    "fifties": 0,
    "wickets": 42,
    "economy": 7.9,
    "bestBowling": "4/15",
    "rating": 90
  },
  {
    "name": "Rajat Patidar",
    "role": "Batter",
    "team": "RCB",
    "basePrice": 110000000,
    "stats": "Runs: 792, SR: 138.2, Avg: 34.43",
    "nationality": "Indian",
    "category": "Retained",
    "isCapped": true,
    "isOverseas": false,
    "poolSource": "2025",
    "espnId": "823703",
    "cricbuzzId": "11808",
    "iplId": "111",
    "runs": 792,
    "strikeRate": 138.2,
    "average": 34.43,
    "hundreds": 1,
    "fifties": 4,
    "wickets": 0,
    "economy": 0,
    "bestBowling": "",
    "rating": 87
  }
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB for seeding 2025 players...');
    
    // Clear old 2025 players
    const deleteResult = await Player.deleteMany({ poolSource: '2025' });
    console.log(`Cleared ${deleteResult.deletedCount} existing 2025 players.`);
    
    // Insert new ones
    const insertResult = await Player.insertMany(players2025);
    console.log(`Successfully seeded ${insertResult.length} authentic IPL 2025 players!`);
    
    await mongoose.disconnect();
    console.log('Database connection closed.');
    process.exit(0);
  } catch (err) {
    console.error('Seeding error:', err);
    process.exit(1);
  }
}

if (require.main === module) {
  seed();
}

module.exports = players2025;
